### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by IGDanie** [GediminasMasaitis/PokeEase#18]
Tried loading the index.html and nothing comes up just the map. No idea why. Clean install of it still nothing?

**Comment by xidus90** [comment]
nurx-pokeease have add Google Maps.

Now we have Google Maps and LeafletMap(old Map).

If used LeafletMap it give this Error on Console "Google Maps API error: MissingKeyMapError"

**Comment by itayganor** [comment]
should work now.
