### ISSUE TITLE
[Enhancement] Allow to click and place lures on pokestops

### ISSUE THREAD

**Issue by PureGore** [GediminasMasaitis/PokeEase#32]
Hi,
It would be really nice if we can click on the pokestops and attach lures on them.

Thanks,

**Comment by Zendrex** [comment]
That would require the rocket api to have a feature to allow lures to be used, then have that integrated within any give bot (like pokemobbot) then, if that was all available, then this could possibly do something like that.

**Comment by GediminasMasaitis** [comment]
Currently impossible - none of the bots support it.
