### ISSUE TITLE
ID's mixed up?

### ISSUE THREAD

**Issue by RuneMykle** [GediminasMasaitis/PokeEase#38]
Clefairy and Eevee gets mixed up when clicking them in "Pokemons"

Same with:

Sandshrew & Magikarp
Caterpie & Psyduck
Venonat & Bellsprout

Theres quite possibly more, but it's a fresh account so got no more pokes to check.

**Comment by GediminasMasaitis** [comment]
I'm not entirely sure because of lack of details, but this probably got fixed by https://github.com/GediminasMasaitis/PokeEase/commit/7192a4d93094782c8b1c081f25f8e2d6701b7ee5 a while ago.

If your problem still persists, reopen this issue with more details.
