### ISSUE TITLE
Bug When Using Launch.bat Not Displaying At All... FIXED...

### ISSUE THREAD

**Issue by masterpowers** [GediminasMasaitis/PokeEase#46]
When Using Launch.bat to Launch your PokeEase 
SOmetimes it Wont Show or Display Info At All...
Ive Tested it , the Fixed is this...

You Need to Add incognito to it...
Just a Simple fix

```
start chrome --app="%CD%\src\index.html" --incognito
```

**Comment by jarlave** [comment]
incognito fixes nothing, it just doesn't load localstorage (settings you make in pokeease), so you don't keep your settings after you close it.
This is also a problem if you only open the html file in browser, have nothing to do with launch.bat

**Comment by GediminasMasaitis** [comment]
Like mentioned by @jarlave , this has nothing to do with incognito. If you encounter this problem again, see if there's anything useful in the chrome console, and re-open an issue.
