### ISSUE TITLE
Location Jumping.

### ISSUE THREAD

**Issue by IGDanie** [GediminasMasaitis/PokeEase#7]
Something causing location to jump randomly across the world. Working on trying to find the reason as to this. Attempting to duplicate this bug. https://gyazo.com/018bc96e12d79b9a081281a2323e3c19

**Comment by IGDanie** [comment]
Was due to zooming out on the map. (ctrl+mouse scroll)

**Comment by GediminasMasaitis** [comment]
Duplicate of #9
